branches:
  - main
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - path: dist/**
  - "@semantic-release/changelog"
