name: lint / renovate

on:
  pull_request:
    paths:
      - .github/workflows/lint--renovate.yaml
      - renovate.json
permissions:
  contents: read
env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: "11.22"
  # renovate: datasource=npm depName=renovate
  RENOVATE_VERSION: "44.39"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # I saw cache upload consume >30s.
      # It takes just 10 and some secs for installing pnpm and renovate. So cache is not necessary
      #- uses: actions/cache@v4
      #  with:
      #    path: ~/.pnpm
      #    key: pnpm@${{ env.PNPM_VERSION }}-renovate@${{ env.RENOVATE_VERSION }}-${{ runner.os }}-${{ runner.arch }}-
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: ${{ env.PNPM_VERSION }}
          dest: ~/.pnpm
      - run: pnpm add -g renovate@${RENOVATE_VERSION}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout: |
            renovate.json
      - run: renovate-config-validator --strict
        env:
          LOG_LEVEL: "warn"
