name: Test
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-lint-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
      - run: cargo --locked fmt
      - id: gh-token-gen
        uses: oakcask/gh-token-gen@e3d2caa8ef6111f5a516995d88890d3fb09206e3 # v5.0.0
        with:
          app-id: ${{ secrets.TOKEN_GEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_GEN_PRIVATE_KEY }}
      - uses: int128/update-generated-files-action@dc76a132136f514f84861a509955aa498d249e56 # v2
        with:
          commit-message: "style: `cargo --locked fmt`"
          token: ${{ steps.gh-token-gen.outputs.token }}
      - run: cargo --locked clippy --fix
      - uses: int128/update-generated-files-action@dc76a132136f514f84861a509955aa498d249e56 # v2
        with:
          commit-message: "fix: `cargo --locked clippy --fix`"
          token: ${{ steps.gh-token-gen.outputs.token }}

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
      - run: cargo --locked test
