name: Test
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-lint-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      - run: cargo --locked fmt
      - id: gh-token-gen
        uses: oakcask/gh-token-gen@d65c585678cb39f009f96046d788617e1d0b0745 # v4.0.2
        with:
          app-id: ${{ secrets.TOKEN_GEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_GEN_PRIVATE_KEY }}
      - uses: int128/update-generated-files-action@f83cd1762d5cde0de059b0e91bf86399662fbb71 # v2
        with:
          commit-message: "style: `cargo --locked fmt`"
          token: ${{ steps.gh-token-gen.outputs.token }}
      - run: cargo --locked clippy --fix
      - uses: int128/update-generated-files-action@f83cd1762d5cde0de059b0e91bf86399662fbb71 # v2
        with:
          commit-message: "fix: `cargo --locked clippy --fix`"
          token: ${{ steps.gh-token-gen.outputs.token }}

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      - run: cargo --locked test
